### ISSUE TITLE
possible data lost

### ISSUE THREAD

**Issue by axet** [MStadlmeier/drivesync#35]
Hello!

If datasync interrupted before first sync is finished (with ctrl+c) next start will start delete files remotely (from google drive).

**Comment by MStadlmeier** [comment]
@axet Hi. I have not been able to reproduce this. This could only happen if the remote files had already been saved to the local manifest but not downloaded yet, which should not happen.

If you can reproduce this yourself (preferably with the remote_deletion option disabled so that you won't lose any actual data), would you mind sharing your manifest file? You can find it under ~/.drivesync/manifest

You can also email it to me privately: info@mstadlmeier.de

**Comment by axet** [comment]
I give up with Google Drive under linux. Too much issues. Moved to YandexDisk
