### ISSUE TITLE
Similar to other error messages

### ISSUE THREAD

**Issue by peepingThomist** [MStadlmeier/drivesync#46]
Drivesync works fine. For many months, these four error messages have appeared:

1. /home/<username>/bin/drivesync/drivesync.rb:11: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
2. /var/lib/gems/2.7.0/gems/mime-types-3.1/lib/mime/types/logger.rb:28: warning: `_1' is reserved for numbered parameter; consider another name
3. /var/lib/gems/2.7.0/gems/mime-types-3.1/lib/mime/types/logger.rb:28: warning: `_2' is reserved for numbered parameter; consider another name
4. /var/lib/gems/2.7.0/gems/mime-types-3.1/lib/mime/types/logger.rb:28: warning: `_3' is reserved for numbered parameter; consider another name

I use the unstable Debian kernel, which tomorrow might be different, but today is: 10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux.

Ruby is version 1:2.7+2. I don't know what version ruby-gems is, because it was not installed from the distro's repository.

There are no performance problems. Thank you for creating Drivesync!

**Comment by MStadlmeier** [comment]
@peepingThomist Sorry for getting back to you so late - GitHub notifications seem to actively try to hide from me!
The 4 messages you posted are only warnings, not errors. The first one is indeed caused by DriveSync, while the other 3 are likely caused by some dependency of the Google Drive API. 
For now, you can ignore all of them. I will get rid of the first one in a future update.
